example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'), 
    path('create-task/', create_task, name='create_task'), 
    path('finished/<int:id>', finished_status, name='finished'),
    path('delete/<int:id>', delete_task, name='delete'), 
    path('json/', todolist_json, name='json'),
    path('ajax/', show_todolist_ajax, name='ajax'),
    path('update/<int:id>', update_ajax, name='update_ajax'),
    path('dlt/<int:id>', delete_ajax, name='delete_ajax'),
    path('add/', add_task, name='add_task')
]

todolist/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.now)
    title = models.CharField(max_length=64)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

class TaskCount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

todolist/forms.py
from django import forms
from todolist.models import Task

class CreateTask(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

todolist/views.py
from datetime import date, datetime
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.core import serializers
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from todolist.models import Task, TaskCount
from todolist.forms import CreateTask

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('todolist:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # login first
            response = HttpResponseRedirect(reverse("todolist:ajax")) # create response
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    user = None
    if request.user.is_authenticated:
        user = request.user
    data_todolist_item = Task.objects.filter(user=user)
    context = {
        'list_item': data_todolist_item,
        'name': user.get_username(),
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    return response

@login_required(login_url='/todolist/login/')
def create_task(request):
    form = CreateTask()
    if request.method == "POST":
        form = CreateTask(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            form.save()
            messages.success(request, 'New task successfully created!')
            return redirect('todolist:show_todolist')

    context = {'form':form, 'name':request.user.get_username(), 'date':datetime.now().strftime('%x')}
    return render(request, 'create_task.html', context)

@login_required(login_url='/todolist/login/')
def finished_status(request, id):
    task = get_object_or_404(Task, pk=id)
    task.is_finished = not task.is_finished
    task.save()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

@login_required(login_url='/todolist/login/')
def delete_task(request, id):
    task = get_object_or_404(Task, pk=id)
    task.delete()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

def todolist_json(request):
    user = None
    if request.user.is_authenticated:
        user = request.user
    data = Task.objects.filter(user=user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    user = None
    if request.user.is_authenticated:
        user = request.user
    context = {
        'name': user.get_username(),
        'date': datetime.now().strftime('%x'),
        'count': Task.objects.filter(user=request.user).count(),
    }
    return render(request, "todolist_ajax.html", context)

@login_required(login_url='/todolist/login/')
def update_ajax(request, id):
    task = get_object_or_404(Task, pk=id)
    task.is_finished = not task.is_finished
    task.save()
    return HttpResponseNotFound()

@login_required(login_url='/todolist/login/')
def delete_ajax(request, id):
    task = get_object_or_404(Task, pk=id)
    task.delete()
    return HttpResponseNotFound()

@login_required(login_url='/todolist/login/')
def add_task(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        description = request.POST.get("description")

        new_task = Task(user=request.user, title=title, description=description)
        new_task.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>New Task Creation</title>
{% endblock meta %}

{% block navbar %}
  <div class="d-flex">
      <a class="navbar-brand" href="">To-Do List</a>
  </div>
  
  <div class="navbar-nav">
      <a class="nav-link" aria-current="page" href="{% url 'example_app:index' %}">Home</a>
  </div>
  
  <div class="collapse navbar-collapse justify-content-end" id="navbarElements">
      <div class="navbar-nav">
          <a class="nav-link" aria-current="page" href="{% url 'todolist:show_todolist' %}">My To-do List</a>
          <a class="nav-link disable"><span class="fas fa-user-alt fa-fw"></span>{{ name }}</a>
          <a class="nav-link" aria-current="page" href="{% url 'todolist:logout' %}">Log out</a>
      </div>
  </div>
  {% endblock navbar %}

{% block content %}

<section class="vh-100" style="background-color: mediumseagreen;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card" style="padding: 16px; border-radius: 1rem">
                <h3>Create a new task</h3>
                <div class="card shadow-2-strong" style="border-radius: 1rem;">
                    <div class="card-body p-2 text-center">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-outline mb-2">
                                <input type="text" class="form-control" name="title" required placeholder="Title">
                            </div>
                            <div class="form-outline mb-4">
                                <textarea type="text" class="form-control" name="description" required placeholder="Task description..." rows="12"></textarea>
                            </div>
                            <p>Task creation date: {{ date }}</p>
                            <button type="submit" class="btn btn-primary btn-block mb-4">Create</button>
                        </form>
                        {% if messages %}  
                            {% for message in messages %}  
                                <p>{{ message }}</p>  
                            {% endfor %}  
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block navbar %}
<div class="d-flex">
    <a class="navbar-brand" href="">To-Do List</a>
</div>

<div class="navbar-nav">
    <a class="nav-link" aria-current="page" href="{% url 'example_app:index' %}">Home</a>
</div>

<div class="collapse navbar-collapse justify-content-end" id="navbarElements">
    <div class="navbar-nav">
        <a class="nav-link" aria-current="page" href="{% url 'todolist:register' %}">Create new account</a>
    </div>
</div>
{% endblock navbar %}

{% block content %}

<!-- Section: Design Block -->
<section class="login-wrapper background-radial-gradient overflow-hidden">
    <style>
      .login-wrapper {
        width: 100%;
        height: 100%;
      }
      .background-radial-gradient {
        position: relative;
        padding: 6%;
        background-color: hsl(147, 50%, 15%);
        background-image: radial-gradient(650px circle at 0% 0%,
            hsl(147, 50%, 35%) 15%,
            hsl(147, 50%, 30%) 35%,
            hsl(147, 50%, 20%) 75%,
            hsl(147, 50%, 18%) 80%,
            transparent 100%),
          radial-gradient(1250px circle at 100% 100%,
            hsl(147, 50%, 45%) 15%,
            hsl(147, 50%, 30%) 35%,
            hsl(147, 50%, 20%) 75%,
            hsl(147, 50%, 19%) 80%,
            transparent 100%);
      }
  
      .bg-glass {
        background-color: hsla(0, 0%, 100%, 0.9) !important;
        backdrop-filter: saturate(200%) blur(25px);
      }
    </style>
  
    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
      <div class="row gx-lg-5 align-items-center mb-5">
        <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
          <h1 class="mt-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
            Log in
          </h1>
          <h5 class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
            Please enter your username and password!
          </h5>
        </div>
  
        <div class="col-lg-6 mb-5 mb-lg-0 position-relative text-center">
          <div class="card bg-glass">
            <div class="card-body px-4 py-5 px-md-5">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-outline mb-4">
                        <input type="text" id="typeUsernameX" name="username" placeholder="Username" class="form-control">
                        <label class="form-label" for="typeUsernameX">Username</label>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="password" id="typePasswordX" name="password" placeholder="Password" class="form-control">
                        <label class="form-label" for="typePasswordX">Password</label>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mb-4">Log in</button>
                    {% if messages %}
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    {% endif %}

                </form>
                    <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}" class="text-black-50 fw-bold">Sign Up</a></p>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block navbar %}
<div class="d-flex">
    <a class="navbar-brand" href="">To-Do List</a>
</div>

<div class="navbar-nav">
    <a class="nav-link" aria-current="page" href="{% url 'example_app:index' %}">Home</a>
</div>

<div class="collapse navbar-collapse justify-content-end" id="navbarElements">
    <div class="navbar-nav">
        <a class="nav-link" aria-current="page" href="{% url 'todolist:login' %}">Log in</a>
    </div>
</div>
{% endblock navbar %}

{% block content %}

<!-- Section: Design Block -->
<section class="text-center" style="margin: 0; height: 100vh">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
          background-color: hsl(147, 50%, 35%);
          height: 300px;
          "></div>
    <!-- Background image -->
  
    <div class="card mx-4 mx-md-5 shadow-5-strong" style="
          margin-top: -100px;
          background: hsla(0, 0%, 100%, 0.8);
          backdrop-filter: blur(30px);
          ">
      <div class="card-body py-5 px-md-5">
  
        <div class="row d-flex justify-content-center">
          <div class="col-lg-8">
            <h2 class="fw-bold mb-5">Register a new account</h2>
            <form method="POST" class="d-flex justify-content-center">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td><input type="submit" class="btn btn-primary btn-block mb-4" name="submit" value="Register"/></td>
                    </tr>
                </table>
            </form>
            {% if messages %}
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>To-Do List</title>
<style>
  .background-radial-gradient {
    background-color: hsl(147, 50%, 15%);
    min-height: 90%;
    padding: 5%;
    text-align: center;
    background-image: radial-gradient(650px circle at 0% 0%,
        hsl(147, 50%, 35%) 15%,
        hsl(147, 50%, 30%) 35%,
        hsl(147, 50%, 20%) 75%,
        hsl(147, 50%, 18%) 80%,
        transparent 100%),
      radial-gradient(1250px circle at 100% 100%,
        hsl(147, 50%, 45%) 15%,
        hsl(147, 50%, 30%) 35%,
        hsl(147, 50%, 20%) 75%,
        hsl(147, 50%, 19%) 80%,
        transparent 100%);
  }
  .card-text {
    font-size: 15px;
  }
  .container {
    align-content: center;
  }
  .task-cards:hover {
    transform: scale(1.1);

  }
</style>
{% endblock meta %}
  
{% block navbar %}
<div class="d-flex">
    <a class="navbar-brand" href="">To-Do List</a>
</div>

<div class="navbar-nav">
    <a class="nav-link" aria-current="page" href="{% url 'example_app:index' %}">Home</a>
    <a class="nav-link" aria-current="page" href="{% url 'todolist:ajax' %}">AJAX-Implemented</a>
</div>

<div class="collapse navbar-collapse justify-content-end" id="navbarElements">
    <div class="navbar-nav">
        <a class="nav-link" aria-current="page" href="{% url 'todolist:create_task' %}">Create a New Task</a>
        <a class="nav-link disable"><span class="fas fa-user-alt fa-fw"></span>{{ name }}</a>
        <a class="nav-link" aria-current="page" href="{% url 'todolist:logout' %}">Log out</a>
    </div>
</div>
{% endblock navbar %}

{% block content %}
<section class="background-radial-gradient overflow-hidden" style="min-height: 100vh">
  <div class="container my-2 ">
    <div class="row">
      {% for item in list_item %}
      <div class="col my-3">
        <div class="card task-cards" style="width: 240px; height: 360px;">
          <div class="card-body">
            <h5 class="card-title mb-0">{{ item.title }}</h5>
            <p class="card-text mt-0">Created {{ item.date }}</p>
            <textarea class="card-text" readonly rows="8" cols="27">{{ item.description }}</textarea>
            <p class="card-text">Finished: {{ item.is_finished }}</p>
            <div class="row">
              <div class="col mx-0">
                <button type="button" class="btn btn-block btn-dark card-text" onclick="location.href='finished/{{ item.id }}'">Update status</button>
              </div>
              <div class="col mx-0">
                <button type="button" class="btn btn-block btn-danger card-text" onclick="location.href='delete/{{ item.id }}'">Delete Task</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>  

{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<title>To-Do List</title>
<style>
  .background-radial-gradient {
    background-color: hsl(147, 50%, 15%);
    min-height: 90%;
    padding: 5%;
    text-align: center;
    background-image: radial-gradient(650px circle at 0% 0%,
        hsl(147, 50%, 35%) 15%,
        hsl(147, 50%, 30%) 35%,
        hsl(147, 50%, 20%) 75%,
        hsl(147, 50%, 18%) 80%,
        transparent 100%),
      radial-gradient(1250px circle at 100% 100%,
        hsl(147, 50%, 45%) 15%,
        hsl(147, 50%, 30%) 35%,
        hsl(147, 50%, 20%) 75%,
        hsl(147, 50%, 19%) 80%,
        transparent 100%);
  }
  .card-text {
    font-size: 15px;
  }
  .container {
    align-content: center;
  }
  .task-cards:hover {
    transform: scale(1.1);

  }
</style>
{% endblock meta %}
  
{% block navbar %}
<div class="d-flex">
    <a class="navbar-brand" href="">To-Do List</a>
</div>

<div class="navbar-nav">
    <a class="nav-link" aria-current="page" href="{% url 'example_app:index' %}">Home</a>
</div>

<div class="collapse navbar-collapse justify-content-end" id="navbarElements">
    <div class="navbar-nav">
        <a class="nav-link" type="button" data-bs-toggle="modal" data-bs-target="#newTaskModal">Create a New Task</a>
        <a class="nav-link disable"><span class="fas fa-user-alt fa-fw"></span>{{ name }}</a>
        <a class="nav-link" type="button" href="{% url 'todolist:logout' %}">Log out</a>
    </div>
</div>
{% endblock navbar %}

{% block content %}
<div class="modal fade" id="newTaskModal" tabindex="-1" aria-labelledby="newTaskModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <form id="form" onsubmit="return false">
        {% csrf_token %}
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="newTaskModalLabel">Create a New Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="form-outline mb-2">
            <input type="text" class="form-control" name="title" required placeholder="Title">
          </div>
          <div class="form-outline mb-4">
            <textarea type="text" class="form-control" name="description" required placeholder="Task description..." rows="12"></textarea>
          </div>
          <p>Task creation date: {{ date }}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary" onclick="createTask()" data-bs-toggle="modal" data-bs-target="#newTaskModal">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>

<section class="background-radial-gradient overflow-hidden" style="min-height: 100vh">
  <div class="container my-2 ">
    <div class="row" id="tasks">
    </div>
  </div>
</section>  

<script>
  var taskCount = {{ count }};

  async function getTodolist() {
    return fetch("{% url 'todolist:json' %}").then((res) => res.json())
  }

  async function refreshTodolist() {
        document.getElementById("tasks").innerHTML = "";
        const todolist = await getTodolist();
        let htmlString = `<div>
    <h3 style="color: white">Items To-Do added:</h3>
    <p style="color: white">${taskCount}</p>
  </div>`;
        todolist.forEach((item) => {
          htmlString += `\n<div class="col my-3">
        <div class="card task-cards" style="width: 240px; height: 360px;">
          <div class="card-body">
            <h6 class="card-title mb-0">${item.fields.title}</h6>
            <p class="card-text mt-0">Created ${item.fields.date}</p>
            <textarea class="card-text" readonly rows="8" cols="27">${item.fields.description}</textarea>
            <p class="card-text">Finished: ${item.fields.is_finished}</p>
            <div class="row">
              <div class="col mx-0">
                <button type="button" class="btn btn-block btn-dark card-text update-btn" id=${item.pk} onclick="updateTask(this.id)">Update status</button>
              </div>
              <div class="col mx-0">
                <button type="button" class="btn btn-block btn-danger card-text delete-btn" id=${item.pk} onclick="deleteTask(this.id)">Delete Task</button>
              </div>
            </div>
          </div>
        </div>
      </div>` 
        });
        
        document.getElementById("tasks").innerHTML = htmlString;
  };

  function updateTask(id) {
    var url = "{% url 'todolist:update_ajax' 1 %}".replace('1', id);
    fetch(url).then(refreshTodolist)
  };

  function deleteTask(id) {
    taskCount -= 1;
    var url = "{% url 'todolist:delete_ajax' 1 %}".replace('1', id);
    fetch(url).then(refreshTodolist)
  };

  function createTask() {
    taskCount += 1;
    fetch("{% url 'todolist:add_task' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#form'))
      }).then(refreshTodolist);
    return false
  };

  $(document).ready(function() {
    $('#newTaskModal').on('hidden.bs.modal', function () {
      $('#newTaskModal').find('form').trigger("reset");
    });
  })

  refreshTodolist()
</script>

{% endblock content %}