example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import *

app_name = 'mywatchlist'

urlpatterns = [
    path('', redirect_to_html, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'), 
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'), 
    path('create-task/', create_task, name='create_task'), 
    path('finished/<int:id>', finished_status, name='finished'),
    path('delete/<int:id>', delete_task, name='delete'), 
    path('json/', todolist_json, name='json'),
    path('ajax/', show_todolist_ajax, name='ajax'),
    path('update/<int:id>', update_ajax, name='update_ajax'),
    path('dlt/<int:id>', delete_ajax, name='delete_ajax'),
    path('add/', add_task, name='add_task')
]

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_wishlist_item = CatalogItem.objects.all()
    context = {
        'list_item': data_wishlist_item,
        'name': 'Mohammad Attar',
        'npm': '2106657992',
    }
    return render(request, "katalog.html", context)

katalog/templates/katalog.html
{% extends 'base.html' %}
 {% block meta %}
  <title>Katalog</title>
 {% endblock meta %}
 
 {% block navbar %}
 <div class="d-flex">
   <a class="navbar-brand" href="#">PBD Assignments</a>
 </div>
 
 <div class="collapse navbar-collapse" id="navbarElements">
   <div class="navbar-nav">
     <a class="nav-link" aria-current="page" href="{% url 'example_app:index' %}">Home</a>
     <a class="nav-link active" aria-current="page" href="{% url 'katalog:show_katalog' %}">Katalog</a>
     <a class="nav-link" aria-current="page" href="{% url 'mywatchlist:show_mywatchlist' %}">Watchlist</a>
     <a class="nav-link" aria-current="page" href="{% url 'todolist:show_todolist' %}">To-Do List</a>
   </div>
 </div>
 {% endblock navbar %}

 {% block content %}
 <div style="padding-top: 64px; height: 100vh">
  <h1>Assignment #2 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{name}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
        <tr>
            <th>{{item.item_name}}</th>
            <th>{{item.item_price}}</th>
            <th>{{item.item_stock}}</th>
            <th>{{item.rating}}</th>
            <th>{{item.description}}</th>
            <th>{{item.item_url}}</th>
        </tr>
    {% endfor %}

  </table>
 </div>
 {% endblock content %}